### ISSUE TITLE
Allow jumping in HTML

### ISSUE THREAD

**Issue by btracey** [cameron/squirt#33] opened 2014-03-13 00:35 UTC
Trying to read, say A Tale of Two Cities, one may want to skip to a certain chapter, for example http://www.gutenberg.org/files/98/98-h/98-h.htm#link2H_4_0016. However, squirt starts at the top of the page.

**Comment by ultimatedelman** [comment] 2014-03-13 01:35
you can highlight what you want to read and then hit squirt

**Comment by btracey** [comment] 2014-03-13 05:12
This does not work for me on the Gutenberg site linked (Firefox 27.0.1, OSX 10.9.2)

**Comment by j6k4m8** [comment] 2014-03-13 19:33
Couldn't reproduce — selection worked fine for me. Can you explain the issue a little more?

**[EDIT]** There is a known bug in Firefox. Check out #45.

**Comment by cameron** [comment] 2014-03-16 00:32
Closing, noted that gutenberg could be better supported.

**Closed as completed by cameron** 2014-03-16 00:32 UTC
