### ISSUE TITLE
Error on squirt at SSL hosted sites. 

### ISSUE THREAD

**Issue by sandrasvensson** [cameron/squirt#49] opened 2014-03-13 11:39 UTC
I get an issue when trying to load squirt on a HTTPS site. For example: https://medium.com. Would it be possible to run it over ssl as well?

**Comment by sturob** [comment] 2014-03-13 12:45
Dupe of https://github.com/cameron/squirt/issues/5

**Closed as completed** 2014-03-16 03:05 UTC
Labels: bug
