### ISSUE TITLE
slow down for big words

### ISSUE THREAD

**Issue by mearns** [cameron/squirt#70] opened 2014-03-13 19:58 UTC
I watched some long words (14 letters) fly by too quickly to read them. It's fine for smaller words, but it would be great if long words were left up a little longer so they can really be taken in.

**Comment by j6k4m8** [comment] 2014-03-13 20:01
Duplicate of #3. A few of us are also considering a version [optimized for academia](https://github.com/j6k4m8/squirt-academic) that lets long words stick for longer so you can fully parse them.

**Closed as completed** 2014-03-16 03:21 UTC
Labels: enhancement
