### ISSUE TITLE
squirt uses keen.io for tracking my usage

### ISSUE THREAD

**Issue by daveloyall** [cameron/squirt#14] opened 2014-03-12 16:53 UTC
https://github.com/cameron/squirt/search?q=keen

What is keen?

I don't know, but I don't like it: https://keen.io/

Cheers,

**Comment by clarkf** [comment] 2014-03-12 18:43
:+1:

It's alright to track while browsing squirt.io, but don't load it each time I use the plugin.

(Note that privacy extensions such as [Ghostery](https://www.ghostery.com/) prevent keen from loading)

**Comment by jayzelenkov** [comment] 2014-03-13 16:12
I agree with @daveloyall . This is a serious invasion into users' privacy!

The fact that all user actions within squirt reader itself (open, close, faster, slower, pause, etc) are being tracked on all sites should be mentioned on the squirt's website and in the README file of the project or removed altogether.

> P.S.
> Adblock Plus doesn't filter these requests.

**Comment by j6k4m8** [comment] 2014-03-13 17:40
:thumbsup: on this. Not a fan of sending URL / IP etc.

**Comment by nomicode** [comment] 2014-03-14 15:31
I think this should be removed completely. Notification isn't good enough.

**Comment by cameron** [comment] 2014-03-15 23:24
First of all, I'm sorry—there absolutely should have been a notification on www.squirt.io from the beginning. There is now a notice on the install page. 

+1 making it configurable, but removing it entirely is not going to happen.

**Comment by nomicode** [comment] 2014-03-15 23:27
That's very disappointing. This tool has no business tracking users at all. :-1:

**Comment by cameron** [comment] 2014-03-15 23:31
Can you help me understand your disappointment in light of a notification and an option to opt-out?

**Comment by nomicode** [comment] 2014-03-15 23:34
Tracking the websites someone visits is an extremely invasive sort of surveillance. There ought to be a very good reason to enable this sort of thing by default. I see no justification for it whatsoever.

**Comment by jayzelenkov** [comment] 2014-03-15 23:51
@cameron statistically most of the users stick to the default settings. This gives you a huge data about who visited what websites and for how long. That data could be analyzed and/or sold to other companies to be analyzed. Not to mention the fact that `squirt` will know when I visit "questionable" websites. It is simply beyond `squirt` concerns.

We are expected to trust you that you keep collected data private. I want to trust you but the problem is that as the number of users is growing you would be more and more tempted to sell the data.

That said, I realize that you as a developer want to know how many users are using your application, and most importantly, _how_ they are using it.

My suggestion is: make data tracking disabled by default and ask people to opt-in to help with the development of the application. Most of the serious applications do that. I also don't want to scare you, but since the code is free, there is essentially a risk for you that some other developer will create a tracking-free version. (especially if more people will get annoyed by this issue)

**Comment by jayzelenkov** [comment] 2014-03-16 00:02
@daveloyall @clarkf @j6k4m8 @nslater 

I've looked into the code and network activities of the [OpenSpritz](https://github.com/Miserlou/OpenSpritz) and it looks like a non-tracking speed-reading alternative.

**Comment by cameron** [comment] 2014-03-16 00:12
@nslater, that's not a response to my question, that's a restatement of your position. The justification is that in order to build a good product, you need to know how users interact with it. 

@jzelenkov, thanks for the thoughtful comments. 

Okay, I support this repo being opt-in to tracking. 

Full disclosure: I plan on consuming it from www.squirt.io such that it is opt-out. 

Closing and opening a new issue to make squirt tracking configurable

**Closed as completed by cameron** 2014-03-16 00:12 UTC
Labels: enhancement

**Comment by cameron** [comment] 2014-03-16 00:20
P.S. Please do not take my closing the issue as me walking away from the conversation. I appreciate the discussion!

**Comment by nomicode** [comment] 2014-03-16 00:26
I don't think that the benefit tracking provides from a product management perspective is worth the violation of user privacy. Not even close. Not sure what else I can add! :)

Glad to see you're making it opt-in.

**Comment by jayzelenkov** [comment] 2014-03-16 00:27
@cameron thank you for being open-minded about this issue.

**Comment by cameron** [comment] 2014-03-16 00:28
> I don't think that the benefit tracking provides from a product management perspective is worth the violation of user privacy. Not even close. Not sure what else I can add! :)

We're just at odds, here :) Which is why I'm glad that I've separated this repo from www.squirt.io, and  hopefully that means we can continue collaborating!
