### ISSUE TITLE
Does not work on kernel.org

### ISSUE THREAD

**Issue by AshKash** [cameron/squirt#40] opened 2014-03-13 05:06 UTC
Was browsing:
https://git.kernel.org/cgit/git/git.git/tree/Documentation/RelNotes/2.0.0.txt

**Comment by daveloyall** [comment] 2014-03-13 17:08
Probably a dupe of #5

**Comment by AshKash** [comment] 2014-03-13 17:36
Confirmed that the problem is due to https. This seems to be working fine:
http://git.kernel.org/cgit/git/git.git/tree/Documentation/RelNotes/2.0.0.txt

**Comment by cameron** [comment] 2014-03-16 02:22
thanks :)

**Closed as completed by cameron** 2014-03-16 02:22 UTC
