### ISSUE TITLE
Stops reading when reaching "i.e."

### ISSUE THREAD

**Issue by chrismanahan** [cameron/squirt#60] opened 2014-03-13 15:46 UTC
When Squirt reaches something like 

```
i.e.
```

it will display

```
i.
```

 and then proceed to be blank and not continue. I think it has to do with the format of the string, I haven't been able to test it with other variations.

**Comment by j6k4m8** [comment] 2014-03-13 17:53
Duplicate of #26.

**Closed as completed** 2014-03-16 03:12 UTC
Labels: bug
